---
- name: "Set up a Matrix server"
  hosts: "{{ target if target is defined else 'matrix_servers' }}"
  become: true

  roles:
    - matrix-base
    - matrix-synapse
    - matrix-riot-web
    - role: matrix-nginx-proxy
      vars:
        matrix_nginx_proxy_https_enabled: false
        matrix_nginx_proxy_base_path: "/matrix/env/infra/nginx-proxy"
        matrix_nginx_proxy_proxy_matrix_client_api_addr_with_container: "{{tenant}}_matrix-synapse:8008"
        matrix_nginx_proxy_proxy_riot_client_api_addr_with_container: "{{tenant}}_matrix-riot-web:8080"
    - role: matrix-nginx-proxy
      vars:
        matrix_nginx_proxy_https_enabled: true
        matrix_nginx_proxy_base_path: "/matrix/env/infra/ssl/nginx-proxy"
        matrix_ssl_config_dir_path: "/matrix/env/infra/ssl/config"
        matrix_nginx_proxy_proxy_matrix_client_api_addr_with_container: "192.168.64.14"
        matrix_nginx_proxy_proxy_riot_client_api_addr_with_container: "192.168.64.14"
    - matrix-common-after
